### ISSUE TITLE
Darknet returning garbage bounding boxes in Qt Event Loop

### ISSUE THREAD

**Issue by isgursoy** [prabindh/qt5-opencv3-darknet#1]
Darknet behaves differently in QCoreApplication/QApplication. It is okay while debugging but run is problematic. Why?

**Comment by prabindh** [comment]
1. Are you using darknet-cpp fork ? Does it work for you outside Qt ?
2. If issue is only when integrating to Qt - please share your call flow and environment/HW/OS.

**Comment by isgursoy** [comment]
Hi,
1) Yes (nothing changes for c version too) and yes. I am facing problem only if there is a Qt event loop alive in somewhere.
2) Yes.
Qt 5.7.1 with gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) on Ubuntu 16.04 x86_64 4.4.0-57-generic kernel.
Compiled with;
GPU=0|1
CUDNN=0
OPENCV=0|1
DEBUG=0|1
Only one function, main;
a) Create QCoreApplication or QApplication instance;
b) Use darknet
c) a.exec
No threading, nothing special. I can share my private repo If more details will be useful for you.

Thanks for your time.

**Comment by isgursoy** [comment]
So what is the point of the c++ port? Your lib/port/whatever is totally useless in Qt without an event loop. Good to solve that.

**Comment by prabindh** [comment]
Just to confirm,  1. The darknet-cpp port works without Qt integration.  Could you share the cmd line you use to test the darknet cpp port 2.  In Qt5,  what signals are you waiting on?

**Comment by isgursoy** [comment]
Please see https://gitlab.com/isgursoy/darknet

utility is a simple test program that uses darknet as a shared library.
src/darknet is cpp version.
src/darknetc comes from pjreddie's repo.
src/private has c++ wrapper over them and finally Darknetlib.hpp is library header.

**Comment by isgursoy** [comment]
https://groups.google.com/forum/#!topic/darknet/LHIwhQ2l3pQ
